# Generated by Django 5.2.4 on 2025-10-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, help_text='Unggah gambar yang relevan dengan materi.', null=True, upload_to=''),
        ),
    ]
